name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # todo: support windows
        go-version: ['1.18', '1.24']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Verify Go version
      run: go version

    - name: Run tests
      run: go test -v -timeout=5m
